### ISSUE TITLE
Some Ideas for more userfriendly use

### ISSUE THREAD

**Issue by jdroo** [proferabg/EdiZon-Overlay#1]
maybe make it so it could detect on and off variants of codes, depending how they are laid out in the text file, like if the two cheats have no paragraph break between them, it would just set the cheat to be listed once, and just click it to activate it, and click it off to deactivate, without showing both separate name codes.

for example you'd format the text file like this:

https://i.imgur.com/D81WPpL.png

so like currently it shows for example in Tesla:

    [Item ++ (On)] ON

    [Item ++ (Off)]

But then instead have it so it shows one:
When toggled on

    [Item ++] ON

When toggled off.

    [Item ++] OFF

of course to make that work, the off toggle would have to turn on then off again so it's not always running... not sure how that could be implemented...

Does that make sense?

of course you'd not be naming it "[Item ++ (On)]" if it worked that way, you'd just name it "[Item ++]". lol

**Comment by jdroo** [comment]
maybe make it so if your at the top and keep going up it just jumps back to the bottom of the cheat list, and visa versa. 

Just some ease of use ideas

**Comment by jdroo** [comment]
Could ya  make it that if you push right or left it would scroll up or down down like full sections like 10 at a time or something to make scrolling thru them all much faster.

**Comment by proferabg** [comment]
I have though about this and some features _**might**_ be implemented with the next push.

**Comment by ImanCol** [comment]
I support this, I did not realize that you could make subfolders or subcategories in which you could access and see the tricks in an orderly way.  So I was wondering if there are more features there, like changing the cheatcode title according to the value manifested by a 64Bit register or reading it from Memory.  It would be very useful for displacements where you can see a descriptive text of what the memory contains.  Or in this case, a cheatcode where, depending on the value you increase, it will show you a specific text of what that value contains (for object ID codes)
