### ISSUE TITLE
Cheats aren't getting loaded

### ISSUE THREAD

**Issue by DebeshMishra** [proferabg/EdiZon-Overlay#13]
Prior to this update, the cheats were working fine. In this update, I just see "No cheats loaded" even though the folder is present in atmosphere/contents folder. Did anything change in between the updates?

**Comment by mayt04** [comment]
What cheats are you trying to use?

**Comment by proferabg** [comment]
Make sure you have the correct application and build id's for your cheats. What game and what version are you trying to use and what is the name of your cheat file?

**Comment by DebeshMishra** [comment]
Nvm I was using the outdated codes. It works fine.
