### ISSUE TITLE
Open cheat list without back to main menu like 1.0.1

### ISSUE THREAD

**Issue by mnbvcxz7412369** [proferabg/EdiZon-Overlay#16]
in the 1.0.1 version, it can close(L + ↓ + right joystick) the tesla overlay when it is in the cheat list, and you can open(L + ↓ + right joystick again) the overlay directly into the cheat list.

but in all other newer versions, when you close overlay in the cheat list, it won't work right after you open back overlay directly into the cheat list, it displays the wrong on/off state, and when you enable cheat in this situation it might enable/disable the wrong cheat. it only works right when you return to the main menu and reload the cheat list.

since the 16.0.0 firmware version doesn't support 1.0.1 anymore, hopefully, this will work like 1.0.1 in the newer version.

**Comment by ELY3M** [comment]
I have same issue.    I noticed too.

**Comment by ELY3M** [comment]
I am able to update the 1.0.1 version to work on 16.0.0 but be aware that the grouping and nesting is not available in that version.

**Comment by ELY3M** [comment]
This is 1.0.1 version working on 16.0.0   
[ovlEdiZon.zip](https://github.com/proferabg/EdiZon-Overlay/files/11053303/ovlEdiZon.zip)

**Comment by ELY3M** [comment]
I hope this help you.    https://github.com/ELY3M/EdiZon-Overlay-1.0.1

**Comment by ELY3M** [comment]
I will try to get the newest version to work like what you wanted.   I also prefer that way too.

**Comment by mnbvcxz7412369** [comment]
Thank you so much!!!!!
I really used to it working that way, it also remembers your last select cheat.
using newer versions keeps making me enable wrong cheats or crash the system, and also causes me to enable cheat without noticing, then save permanent changes I don't want into my save file.

**Comment by proferabg** [comment]
I am looking into the issue of cheats not matching up. I will post an update when it is fixed.

**Comment by ELY3M** [comment]
are we talking about this issue as seen in this video?   
https://youtu.be/eaHjc0V2DGU

**Comment by proferabg** [comment]
The cheats not matching up should be fixed in version [1.0.7](https://github.com/proferabg/EdiZon-Overlay/releases/tag/v1.0.7) as well as a new feature to disable submenu logic for anyone who desires to use it (usage on [readme](https://github.com/proferabg/EdiZon-Overlay#readme)).
