### ISSUE TITLE
UI taking longer than normal to load (v1.0.6 -> v1.0.7)

### ISSUE THREAD

**Issue by ppkantorski** [proferabg/EdiZon-Overlay#18]
I did some tests with v1.0.6 and v1.0.7.  For some reason v1.0.7 takes longer than normal to load.  It still loads, but v1.0.6 is almost instant while v1.0.7 takes a second or two.  Know what the issue might be?

**Comment by ppkantorski** [comment]
Hey again, I actually resolved this issue on my fork.  By any chance, would you be interested in a PR?  I've also rebuilt Edizon Overlay with the latest [libultrahand](https://github.com/ppkantorski/libultrahand) and applied a number of fixes.

I labeled it 1.0.9, but if you want I can hand off my changes to you since you are the one currently managing Edizon Overlay.

Let me know your thoughts when you get the chance. Thx.

**Comment by proferabg** [comment]
Yeah, make a PR for sure. I will build it and have it submitted to the store as soon as I can.
