### ISSUE TITLE
In hos 14.0.0, the CPU and PCB temperature shows 0℃

### ISSUE THREAD

**Issue by lsp199308** [proferabg/EdiZon-Overlay#2]

**Comment by proferabg** [comment]
I am looking into this. With atmosphere being pre-release software right now, a build might not be pushed until it is released as stable.

**Comment by proferabg** [comment]
The function for grabbing temperatures has been removed in `14.0.0`, explained here switchbrew/libnx#588. If I find alternative method, I will reopen and fix this issue.

**Comment by proferabg** [comment]
The function being called `tsGetTemperatureMilliC` was removed in 14.0.0. I am pushing an update to use an alternative method.

**Comment by Kalmito** [comment]
THX for FIX! :)
