### ISSUE TITLE
Firmware 17.0.0 shows 0 temperatures 

### ISSUE THREAD

**Issue by curcius** [proferabg/EdiZon-Overlay#20]
Temperature values show zero values after updating to the latest version 17.0.0, hbmenu shows, status monitor too.

**Comment by curcius** [comment]
![20231028_060531](https://github.com/proferabg/EdiZon-Overlay/assets/1108722/f8b83461-f121-4589-9a57-3ba76d8de162)

**Comment by curcius** [comment]
Will there be no more updates?

**Comment by proferabg** [comment]
I have been very busy. You are free to make a pull-request if you like, otherwise, I will update it when I get a chance.

**Comment by proferabg** [comment]
Fixed in next update. Stay tuned. Should be up later today.
