### ISSUE TITLE
Remember enabled cheats

### ISSUE THREAD

**Issue by Lyzing** [proferabg/EdiZon-Overlay#21]
It would be great if there's another toggle at the very top or bottom were we could decide if it should auto enable the current enabled cheats next time when the game starts eventually with a small delay like 10 seconds after game start.

There're so many graphic cheats for some games, it would be nice to save the best settings we found and auto load them always

I'm not sure if this is something you can do on your end or if it needs to be done on Edizon itself

**Comment by Justman100** [comment]
@proferabg
