### ISSUE TITLE
UI Tip Questions

### ISSUE THREAD

**Issue by a1191500** [proferabg/EdiZon-Overlay#23]
Why not simply display the temperature directly above the UI, eliminating the need to click a button? It seems redundant.

**Comment by proferabg** [comment]
> Why not simply display the temperature directly above the UI, eliminating the need to click a button? It seems redundant.

This was not an original UI by me. I only took over this project and updated it as well as added features. The stats section also displays clock speeds, IP address, and WiFi signal strength. If you want an overlay just to display temperatures in a small form factor without clicking through menus, I suggest looking at [status monitor overlay](https://github.com/masagrator/Status-Monitor-Overlay).
