### ISSUE TITLE
Potential sleep mode issues 

### ISSUE THREAD

**Issue by masagrator** [proferabg/EdiZon-Overlay#27]
Reposting sys-clk issue regarding the same portion of code, I recommend to either remove temperatures, move to GetTemperatureWithError (not tested if it solves issue, function is not available in libnx, you can find it in switchbrew wiki, works only with 17.0.0+) or move to i2c like I did with status monitor overlay. 

https://github.com/retronx-team/sys-clk/issues/85

**Comment by ppkantorski** [comment]
I already migrated to i2c on my PR (heads up)
