### ISSUE TITLE
15.0.0 support

### ISSUE THREAD

**Issue by Arch9SK7** [proferabg/EdiZon-Overlay#6]
on HOS 15.0.0 the overlay just hangs and crashes tesla when opening this overlay. 

if you find the time to fix support for it, this would be wonderful.

**Comment by ELY3M** [comment]
I am having same issue too.  I have to use zing for now.

**Comment by lowburger** [comment]
For me same, problem also exist on original version from WerWolv.

**Comment by proferabg** [comment]
I will check on this today and diagnose after I update to HOS 15.0.0. Thank you all for the heads up.

**Comment by Arch9SK7** [comment]
The issue is in the service sessions for reading system information. Btw  @proferabg

**Comment by proferabg** [comment]
I am going to leave this issue open for a few more days in case more issues arise from HOS 15.0.0 so please let me know if anything else is broken, other than the Wifi Signal level as I am looking into making that work again.

**Comment by lowburger** [comment]
Great thx!

**Comment by Talasha** [comment]
Hi, I found one issue when testing cheats in Animal Crossing: New Horizon. When I activate Tesla - click "Edizon - Cheats" - turn on a cheat - Close Tesla directly by shortcut, it works well. But when I access Tesla by shortcut again and toggle another cheat, it goes wrong. Some cheats cannot be toggled, some are toggled but goes error. Now if I want to toggle a cheat, I have to return to the upper menu "Cheats" and access the "Cheats" again.

**Comment by proferabg** [comment]
> Hi, I found one issue when testing cheats in Animal Crossing: New Horizon. When I activate Tesla - click "Edizon - Cheats" - turn on a cheat - Close Tesla directly by shortcut, it works well. But when I access Tesla by shortcut again and toggle another cheat, it goes wrong. Some cheats cannot be toggled, some are toggled but goes error. Now if I want to toggle a cheat, I have to return to the upper menu "Cheats" and access the "Cheats" again.

Can you post your cheats file so that I can test.

**Comment by proferabg** [comment]
> Sure. Here is the cheat file. [747A5B4CBC530AED.txt](https://github.com/proferabg/EdiZon-Overlay/files/9796171/747A5B4CBC530AED.txt)
I tested this cheat file and found that most of these you need to turn on then back off, otherwise they will overwrite others. I did not find any other issues and since there are no other HOS 15 errors, I am going to close this issue.
