### ISSUE TITLE
Overlay not showing after resizing the screen

### ISSUE THREAD

**Issue by e0v1a** [proferabg/EdiZon-Overlay#7]
Hello, thank you very much for this excellent software
Because my monitor is relatively large, and I can't step back far enough, so usually I adjust the screen size to 80% when in TV mode, and I find that the popup does not display properly in this case, I can feel it It is awakened but cannot be displayed normally (because the screen will be prohibited and you need to press the B key to cancel), but it works normally in handheld mode or TV mode with 100% screen size

Hope this can be fixed, thanks a lot

**Comment by proferabg** [comment]
Does this happen with all overlays or just EdiZon-Overlay?

**Comment by e0v1a** [comment]
It  happens in all overlays, so maybe it's tesla problem?

**Comment by e0v1a** [comment]
I found this issue, it seems to be Tesla's problem, thank you for your time
https://github.com/WerWolv/Tesla-Menu/issues/34
