### ISSUE TITLE
Support for version 16.0.0

### ISSUE THREAD

**Issue by Aaron45678** [proferabg/EdiZon-Overlay#8]
it is broken after atmos update so are you aware of this and know to update it?

**Comment by proferabg** [comment]
An update is on the way. It takes time and the update only just came out.

**Comment by Aaron45678** [comment]
thanks for the reply mate, it is much appreciated. I understand it takes time just wanted to make sure it was known

**Comment by proferabg** [comment]
I am going to close this as completed with support being added with version v1.0.4.
